pub mod day1;
pub mod day2;
pub mod day3;
pub mod day4;
pub mod day5;
pub mod day6;
pub mod day7;
pub mod day8;
pub mod day9;
pub mod day10;
pub mod day11;
pub mod day12;
pub mod day13;
pub mod day14;
pub mod day15;
pub mod day16;
pub mod day17;
pub mod day18;
pub mod day19;
pub mod day20;

fn main() {
    // day1::run();
    // day2::run();
    // day3::run();
    // day4::run();
    // day5::run();
    // day6::run();
    // day7::run();
    // day8::run();
    // day9::run();
    // day10::run();
    // day11::run();
    // day12::run();
    // day13::run();
    // day14::run();
    // day15::run();
    // day16::run();
    // day17::run();
    // day18::run();
    // day19::run();
    day20::run();
}
